routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/about', function () {
    return view('about');
});

Route::get('/contact', function () {
    return view('contact');
});

Route::get('/viewTours', function(){
  return view('viewTours');
});

Route::get('/viewPackages', function(){
  return view('viewPackages');
});

Route::get('/viewTeamMembers', function(){
  return view('viewTeam');
});

/*Route::get('/tours', function () {
    return view('viewAllTours');
});*/

Route::resource('/contactrequests', 'ContactRequestController');

Route::get('/login-panel', 'UserController@loginpanel');
Route::get('/register-panel', 'UserController@registerpanel');

Auth::routes();

Route::get('/logout', 'UserController@logout');

//Counts
Route::resource('/counts', 'CountController');
Route::get('/counts_changestatus/{id}', 'CountController@changestatus');

//Toasts
Route::resource('/toasts', 'ToastController');
Route::get('/toasts_changestatus/{id}', 'ToastController@changestatus');

//Features
Route::resource('/features', 'FeatureController');
Route::get('/features_changestatus/{id}', 'FeatureController@changestatus');

//About us
Route::resource('/aboutus', 'AboutusController');
Route::get('/aboutus_changestatus/{id}', 'AboutusController@changestatus');
Route::get('/deleteLargeImage/{id}', 'AboutusController@deleteLargeImage');

//Contact Request
Route::get('/contactrequests_changestatus/{id}', 'ContactRequestController@changestatus');
Route::get('/contactrequests_delete/{id}', 'ContactRequestController@destroy');

//Queries
Route::resource('/queries', 'QueryController');
Route::get('/queries_changestatus/{id}', 'QueryController@changestatus');

//Gallery
Route::resource('/gallery', 'GalleryController');
Route::get('/gallery_changestatus/{id}', 'GalleryController@changestatus');

//Search Form Image
Route::resource('/searchformimages', 'SearchFormImageController');
Route::get('/searchformimages_changestatus/{id}', 'SearchFormImageController@changestatus');

//Headers
Route::resource('/header', 'HeaderController');
Route::get('/header_changestatus/{id}', 'HeaderController@changestatus');

//Addresses
Route::resource('/addresses', 'AddressController');
Route::get('/addresses_changestatus/{id}', 'AddressController@changestatus');

//Contact
Route::resource('/contacts', 'ContactController');
Route::get('/contacts_changestatus/{id}', 'ContactController@changestatus');

//Emails
Route::resource('/emails', 'EmailController');
Route::get('/emails_changestatus/{id}', 'EmailController@changestatus');

//Socials
Route::resource('/socials', 'SocialController');
Route::get('/socials_changestatus/{id}', 'SocialController@changestatus');

//Cities
Route::resource('/cities', 'CityController');
Route::get('/cities_changestatus/{id}', 'CityController@changestatus');

//Team
Route::resource('/teamMembers', 'TeamMemberController');
Route::get('/teamMembers_changestatus/{id}', 'TeamMemberController@changestatus');

//Tour
Route::resource('/tours', 'TourController');
Route::get('/deleteTourImage/{id}/{tourid}', 'TourController@deleteTourImage');
Route::get('/tours_changestatus/{id}', 'TourController@changestatus');


//Package
Route::resource('/packages', 'PackageController');
Route::get('/deletePackageImage/{id}/{packageid}', 'PackageController@deletePackageImage');
Route::get('/packages_changestatus/{id}', 'PackageController@changestatus');

//Images
Route::resource('/headerImages', 'ImageController');
Route::get('/headerImages_changestatus/{id}', 'ImageController@changestatus');

//Booking
Route::resource('/bookings', 'BookingController');
Route::get('/bookings_changestatus/{id}', 'BookingController@changestatus');

app/Aboutus.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Aboutus extends Model
{
    protected $table = 'aboutus';
}

app/Address.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Address extends Model
{
    //
}

app/Booking.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Booking extends Model
{
    //
}

app/City.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class City extends Model
{
    //
}

app/Contact.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    //
}

app/ContactRequest.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ContactRequest extends Model
{
    //
}

app/Count.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Count extends Model
{
    //
}

app/Email.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Email extends Model
{
    //
}

app/Feature.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Feature extends Model
{
    //
}

app/Gallery.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Gallery extends Model
{
    //
}

app/Header.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Header extends Model
{
    //
}

app/Image.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Image extends Model
{
    //
}

app/Query.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Query extends Model
{
    //
}

app/SearchFormImage.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SearchFormImage extends Model
{
    //
}

app/Social.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Social extends Model
{
    //
}

app/TeamMember.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class TeamMember extends Model
{
    //
}

app/Toast.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Toast extends Model
{
    //
}

app/Tour.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tour extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Contracts\Auth\CanResetPassword;
class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/dashboard/aboutus.blade.php
@extends('dashboard.dashboardlayout')
@section('content')
<div class="content">
  <div class="row">
    <div class="col-md-12">
      <?php
      $aboutusAll = \App\Aboutus::all();
      ?>
      @if(!isset($aboutus) && $aboutusAll->isEmpty())
      <div class="card">
        <div class="card-header">
          <h5 class="title">Add About Us</h5>
        </div>
        <div class="card-body">
          <form role="form" action="/aboutus" method="post" enctype="multipart/form-data">
            {{ csrf_field() }}
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <label>Title</label>
                  <input type="text" class="form-control" placeholder="Title" name="title" required>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label>Large Image</label><small> (Only .png, .jpg, .jpeg accepted)</small><br>
                  <button class="btn btn-primary">
                    Choose Files<input type="file" class="form-control" name="largeImage" accept=".jpg,.jpeg,.png">
                  </button>
                </div>
              </div>
              <div class="col-md-6" hidden>
                <div class="form-group">
                  <label>Small Image</label><small> (Only .png, .jpg, .jpeg accepted)</small><br>
                  <button class="btn btn-primary">
                    Choose Files<input type="file" class="form-control" name="smallImage" accept=".jpg,.jpeg,.png">
                  </button>
                </div>
              </div>
              <div class="col-md-12">
                <div class="form-group">
                  <label>Details</label>
                  <textarea rows="10" class="form-control" placeholder="Details" name="detail"></textarea>
                </div>
              </div>
            </div>
            <button type="submit" class="btn btn-round btn-success pull-right">Submit</button>
          </form>
        </div>
      </div>
      @else
      <div class="card">
        <?php
        $aboutus = \App\Aboutus::where('status', 'Active')->first();
        ?>
        <div class="card-header">
          <h5 class="title">Edit About us</h5>
        </div>
        <div class="card-body">
          <div class="row">
            @if(!empty($aboutus->largeImage))
            <div class="col-md-6 text-center">
              <img src="{{asset('aboutpage/images/').'/'.$aboutus->largeImage}}" alt="Large Image" />
              <a type="link" class="btn btn-danger btn-sm" href="/deleteLargeImage/<?php echo $aboutus->id; ?>">Delete</a>
            </div>
            @endif
            @if(!empty($aboutus->smallImage))
            <div class="col-md-6 text-center">
              <img src="{{asset('aboutpage/images/').'/'.$aboutus->smallImage}}" alt="Small Image" />
              <a type="link" class="btn btn-danger btn-sm" href="/deleteSmallImage/<?php echo $aboutus->id; ?>">Delete</a>
            </div>
            @endif
          </div>

          <form role="form" action="/aboutus/<?php echo $aboutus->id;?>" method="post" enctype="multipart/form-data">
            {{ csrf_field() }}
            {{method_field('PUT')}}
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <label>Title</label>
                  <input type="text" class="form-control" placeholder="Title" name="title" required value="{{$aboutus->title}}">
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label>Large Image</label><small> (Only .png, .jpg, .jpeg accepted)</small><br>
                  <button class="btn btn-primary">
                    Choose Files<input type="file" class="form-control" name="largeImage" accept=".jpg,.jpeg,.png">
                  </button>
                </div>
              </div>
              <div class="col-md-6" hidden>
                <div class="form-group">
                  <label>Small Image</label><small> (Only .png, .jpg, .jpeg accepted)</small><br>
                  <button class="btn btn-primary">
                    Choose Files<input type="file" class="form-control" name="smallImage" accept=".jpg,.jpeg,.png">
                  </button>
                </div>
              </div>
              <div class="col-md-12">
                <div class="form-group">
                  <label>Details</label>
                  <textarea rows="10" class="form-control" placeholder="Details" name="detail">{{$aboutus->detail}}</textarea>
                </div>
              </div>
            </div>
            <button type="submit" class="btn btn-round btn-success pull-right">Submit</button>
          </form>
        </div>
      </div>
      @endif
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">About Us</h4>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table">
              <thead class=" text-primary">
                <tr>
                  <th>Id</th>
                  <th>Title</th>
                  <th>Large Image</th>
                  <th hidden>Small Image</th>
                  <th>Status</th>
                  <th class="text-right">Control Section</th>
                </tr>
              </thead>
              <tbody>
                <?php
                $aboutus = \App\Aboutus::all();
                ?>
                @foreach($aboutus as $value)
                <tr>
                  <td>{{$value->id}}</td>
                  <td>{{$value->title}}</td>
                  <td>
                    @if(!empty($value->largeImage))
                    <img src="{{asset('aboutpage/images/').'/'.$value->largeImage}}" alt="Large Image" width="100" height="100" />
                    @endif
                  </td>
                  <td hidden>
                    @if(!empty($value->smallImage))
                    <img src="{{asset('aboutpage/images/').'/'.$value->smallImage}}" alt="Small Image" width="100" height="100" />
                    @endif
                  </td>
                  <td>{{$value->status}}</td>
                  <td class="text-right">
                    <a type="link" class="btn btn-default btn-sm" href="/aboutus_changestatus/<?php echo $value->id;?>">Change Status</a>
                    <a type="link" class="btn btn-warning btn-sm" href="/about">View</a>
                    <a type="link" class="btn btn-info btn-sm" href="/aboutus/<?php echo $value->id;?>/edit">Edit</a>
                    <form action="{{ route('aboutus.destroy', $value->id) }}" method="post" style="display:inline">
                      {{ method_field('DELETE') }}
                      {{ csrf_field() }}
                      <input type="submit" class="btn btn-danger btn-sm" placeholder="Delete" value="Delete"/>
                    </form>
                  </td>
                </tr>
                @endforeach
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/dashboard/bookings.blade.php
@extends('dashboard.dashboardlayout')
@section('content')
<div class="content">
  <div class="row">
    <div class="col-md-12">
      @if(isset($booking))
      <div class="card">
        <div class="card-header">
          <h5 class="title">View Booking</h5>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-md-4">
              <label>Name:</label>
              @if(!empty($booking->name))
              <span>{{$booking->name}}</span>
              @endif
            </div>
            <div class="col-md-4">
              <label>Phone:</label>
              @if(!empty($booking->phone))
              <span>{{$booking->phone}}</span>
              @endif
            </div>
            <div class="col-md-4">
              <label>Email:</label>
              @if(!empty($booking->email))
              <span>{{$booking->email}}</span>
              @endif
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <label>Message:</label>
              <span>{{$booking->message}}</span>
            </div>
          </div>
        </div>
      </div>
      @endif
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">Bookings</h4>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table">
              <thead class=" text-primary">
                <tr>
                  <th>Id</th>
                  <th>Name</th>
                  <th>Phone</th>
                  <th>Email</th>
                  <th>Booking For</th>
                  <th>Status</th>
                  <th class="text-right">Control Section</th>
                </tr>
              </thead>
              <tbody>
                <?php
                $bookings = \App\Booking::all();
                ?>
                @foreach($bookings as $booking)
                <tr>
                  <td>{{$booking->id}}</td>
                  <td>{{$booking->name}}</td>
                  <td>{{$booking->phone}}</td>
                  <td>{{$booking->email}}</td>
                  <td>
                    <?php
                    $tour = \App\Tour::find($booking->tourId);
                    ?>
                    @if($tour->type === 'Custom')
                    <a href="/tours/{{$tour->id}}">{{$booking->tourId}}</a>
                    @else
                    <a href="/packages/{{$tour->id}}">{{$booking->tourId}}</a>
                    @endif
                  </td>
                  <td>{{$booking->status}}</td>
                  <td class="text-right">
                    <a type="link" class="btn btn-default btn-sm" href="/bookings_changestatus/<?php echo $booking->id;?>">Change Status</a>
                    <a type="link" class="btn btn-warning btn-sm" href="/bookings/<?php echo $booking->id;?>">View</a>
                    <form action="{{ route('bookings.destroy', $booking->id) }}" method="post" style="display:inline">
                      {{ method_field('DELETE') }}
                      {{ csrf_field() }}
                      <input type="submit" class="btn btn-danger btn-sm" placeholder="Delete" value="Delete"/>
                    </form>
                  </td>
                </tr>
                @endforeach
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/dashboard/cities.blade.php
@extends('dashboard.dashboardlayout')
@section('content')

  <div class="content">
    <div class="row">
      <div class="col-md-12">
        @if(!isset($city))
        <div class="card">
          <div class="card-header">
            <h5 class="title">Add City</h5>
          </div>
          <div class="card-body">
            <form role="form" action="/cities" method="post" enctype="multipart/form-data">
              {{ csrf_field() }}
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <label>City</label>
                    <input type="text" class="form-control" placeholder="City" name="name" required>
                  </div>
                </div>
              </div>
              <button type="submit" class="btn btn-round btn-success pull-right">Submit</button>
            </form>
          </div>
        </div>
        @else
        <div class="card">
          <div class="card-header">
            <h5 class="title">Edit City</h5>
          </div>
          <div class="card-body">
            <form role="form" action="/cities/<?php echo $city->id;?>" method="post" enctype="multipart/form-data">
              {{ csrf_field() }}
              {{method_field('PUT')}}
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <label>City</label>
                    <input type="text" class="form-control" placeholder="City" name="name" required value="{{$city->name}}">
                  </div>
                </div>
              </div>
              <button type="submit" class="btn btn-round btn-success pull-right">Submit</button>
            </form>
          </div>
        </div>
        @endif
        <div class="card">
          <div class="card-header">
            <h4 class="card-title">Cities</h4>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table">
                <thead class=" text-primary">
                  <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Status</th>
                    <th class="text-right">Control Section</th>
                  </tr>
                </thead>
                <tbody>
                  <?php
                  $cities = \App\City::all();
                  ?>
                  @foreach($cities as $city)
                  <tr>
                    <td>{{$city->id}}</td>
                    <td>{{$city->name}}</td>
                    <td>{{$city->status}}</td>
                    <td class="text-right">
                      <a type="link" class="btn btn-default btn-sm" href="/cities_changestatus/<?php echo $city->id;?>">Change Status</a>
                      <a type="link" class="btn btn-info btn-sm" href="/cities/<?php echo $city->id;?>/edit">Edit</a>
                      <form action="{{ route('cities.destroy', $city->id) }}" method="post" style="display:inline">
                        {{ method_field('DELETE') }}
                        {{ csrf_field() }}
                        <input type="submit" class="btn btn-danger btn-sm" placeholder="Delete" value="Delete"/>
                      </form>
                    </td>
                  </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

@endsection

resources/views/dashboard/counts.blade.php
@extends('dashboard.dashboardlayout')
@section('content')
  <div class="content">
    <div class="row">
      <div class="col-md-12">
        @if(!isset($count))
        <div class="card">
          <div class="card-header">
            <h5 class="title">Add Count</h5>
          </div>
          <div class="card-body">
            <form role="form" action="/counts" method="post" enctype="multipart/form-data">
              {{ csrf_field() }}
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label>Title</label>
                    <input type="text" class="form-control" placeholder="Title" name="title" required>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label>Count</label>
                    <input type="number" class="form-control" placeholder="Count" name="count" required>
                  </div>
                </div>
                <div class="col-md-12">
                  <div class="form-group">
                    <label>Image</label><small>Size: 48*48 (Only .png, .jpg, .jpeg accepted)</small><br>
                    <button class="btn btn-primary">
                      Choose File<input type="file" class="form-control" name="image" accept=".jpg,.jpeg,.png" required>
                    </button>
                  </div>
                </div>
              </div>
              <button type="submit" class="btn btn-round btn-success pull-right">Submit</button>
            </form>
          </div>
        </div>
        @else
        <div class="card">
          <div class="card-header">
            <h5 class="title">Edit Count</h5>
          </div>
          <div class="card-body">
            <div class="row">
              <div class="col-md-3">
                <img src="{{asset('count/images/').'/'.$count->picturePath}}" alt="Feature Image" width="48" height="48" />
              </div>
            </div>
            <form role="form" action="/counts/<?php echo $count->id;?>" method="post" enctype="multipart/form-data">
              {{ csrf_field() }}
              {{method_field('PUT')}}
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label>Title</label>
                    <input type="text" class="form-control" placeholder="Title" name="title" value="{{$count->title}}">
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label>Count</label>
                    <input type="number" class="form-control" placeholder="Count" name="count" value="{{$count->count}}">
                  </div>
                </div>
                <div class="col-md-12">
                  <div class="form-group">
                    <label>Image</label><small>Size: 48*48 (Only .png, .jpg, .jpeg accepted)</small><br>
                    <button class="btn btn-primary">
                      Choose File<input type="file" class="form-control" name="image" accept=".jpg,.jpeg,.png">
                    </button>
                  </div>
                </div>
              </div>
              <button type="submit" class="btn btn-round btn-success pull-right">Submit</button>
            </form>
          </div>
        </div>
        @endif
        <div class="card">
          <div class="card-header">
            <h4 class="card-title">Counts</h4>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table">
                <thead class=" text-primary">
                  <tr>
                    <th>Id</th>
                    <th>Image</th>
                    <th>Title</th>
                    <th>Count</th>
                    <th>Status</th>
                    <th class="text-right">Control Section</th>
                  </tr>
                </thead>
                <tbody>
                  <?php
                  $counts = \App\Count::all();
                  ?>
                  @foreach($counts as $value)
                  <tr>
                    <td>{{$value->id}}</td>
                    <td><img src="{{asset('count/images/').'/'.$value->picturePath}}" alt="Feature Image" width="48" height="48" /></td>
                    <td>{{$value->title}}</td>
                    <td>{{$value->count}}</td>
                    <td>{{$value->status}}</td>
                    <td class="text-right">
                      <a type="link" class="btn btn-default btn-sm" href="/counts_changestatus/<?php echo $value->id;?>">Change Status</a>
                      <a type="link" class="btn btn-info btn-sm" href="/counts/<?php echo $value->id;?>/edit">Edit</a>
                      <form action="{{ route('counts.destroy', $value->id) }}" method="post" style="display:inline">
                        {{ method_field('DELETE') }}
                        {{ csrf_field() }}
                        <input type="submit" class="btn btn-danger btn-sm" placeholder="Delete" value="Delete"/>
                      </form>
                    </td>
                  </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

@endsection

resources/views/dashboard/searchformimages.blade.php
@extends('dashboard.dashboardlayout')
@section('content')

  <div class="content">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            <h5 class="title">Add Search Form Image</h5>
          </div>
          <div class="card-body">
            <form role="form" action="/searchformimages" method="post" enctype="multipart/form-data">
              {{ csrf_field() }}
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <label>Image</label><small> (Only .png, .jpg, .jpeg accepted)</small><br>
                    <button class="btn btn-primary">
                      Choose File<input type="file" class="form-control" name="image" accept=".jpg,.jpeg,.png" required>
                    </button>
                  </div>
                </div>
              </div>
              <button type="submit" class="btn btn-round btn-success pull-right">Submit</button>
            </form>
          </div>
        </div>
        <div class="card">
          <div class="card-header">
            <h4 class="card-title">Search Form Images</h4>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table">
                <thead class=" text-primary">
                  <tr>
                    <th>Id</th>
                    <th>Image</th>
                    <th>Status</th>
                    <th class="text-right">Control Section</th>
                  </tr>
                </thead>
                <tbody>
                  <?php
                  $searchformimages = \App\SearchFormImage::all();
                  ?>
                  @foreach($searchformimages as $searchformimage)
                  <tr>
                    <td>{{$searchformimage->id}}</td>
                    <td><img src="{{asset('formimages/images/').'/'.$searchformimage->picturePath}}" alt="Search Form Image" width="100" height="100" /></td>
                    <td>{{$searchformimage->status}}</td>
                    <td class="text-right">
                      <a type="link" class="btn btn-default btn-sm" href="/searchformimages_changestatus/<?php echo $searchformimage->id;?>">Change Status</a>
                      <form action="{{ route('searchformimages.destroy', $searchformimage->id) }}" method="post" style="display:inline">
                        {{ method_field('DELETE') }}
                        {{ csrf_field() }}
                        <input type="submit" class="btn btn-danger btn-sm" placeholder="Delete" value="Delete"/>
                      </form>
                    </td>
                  </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection